# -*- coding: utf-8 -*-
"""task_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng8bY3kHaCik2V2radTvjYVRc5r-fQAG
"""

#task 5
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz
import sys

# ─────────────────────────────
# TIME GATE (3 PM – 5 PM IST)
# ─────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now = datetime.now(ist)

if not (15 <= now.hour < 17):
    print("⛔ This graph is available only between 3 PM – 5 PM IST")
    sys.exit()

print("✅ Time condition satisfied")

# ─────────────────────────────
# LOAD DATA
# ─────────────────────────────
df = pd.read_csv("Play Store Data.csv")

# ─────────────────────────────
# CLEAN DATA
# ─────────────────────────────
df = df.dropna(subset=['Category', 'Installs', 'Reviews', 'Rating', 'Size', 'Last Updated'])

# Clean installs
df['Installs'] = (
    df['Installs'].astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

# Convert size
def convert_size(x):
    x = str(x)
    if 'M' in x:
        return float(x.replace('M', ''))
    elif 'k' in x:
        return float(x.replace('k', '')) / 1024
    return None

df['Size_MB'] = df['Size'].apply(convert_size)

# Convert date
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')

df = df.dropna(subset=['Installs', 'Reviews', 'Rating', 'Size_MB', 'Last Updated'])

# ─────────────────────────────
# APPLY FILTERS
# ─────────────────────────────

# Avg rating ≥ 4.0
df = df[df['Rating'] >= 4.0]

# Size ≥ 10 MB
df = df[df['Size_MB'] >= 10]

# Last updated month = January
df = df[df['Last Updated'].dt.month == 1]

# ─────────────────────────────
# TOP 10 CATEGORIES BY INSTALLS
# ─────────────────────────────
top_categories = (
    df.groupby('Category')['Installs']
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .index
)

df = df[df['Category'].isin(top_categories)]

# ─────────────────────────────
# AGGREGATION
# ─────────────────────────────
agg_df = df.groupby('Category').agg(
    Avg_Rating=('Rating', 'mean'),
    Total_Reviews=('Reviews', 'sum')
).reset_index()

# ─────────────────────────────
# GROUPED BAR CHART
# ─────────────────────────────
fig = go.Figure()

# Average Rating bars
fig.add_trace(go.Bar(
    x=agg_df['Category'],
    y=agg_df['Avg_Rating'],
    name='Average Rating'
))

# Total Reviews bars
fig.add_trace(go.Bar(
    x=agg_df['Category'],
    y=agg_df['Total_Reviews'],
    name='Total Reviews'
))

# ─────────────────────────────
# LAYOUT
# ─────────────────────────────
fig.update_layout(
    title="Average Rating vs Total Reviews (Top 10 Categories)<br><sup>Filters: Rating≥4 | Size≥10MB | January Data</sup>",
    xaxis_title="App Category",
    yaxis_title="Values",
    barmode='group',
    plot_bgcolor="#0a0e1a",
    paper_bgcolor="#111827",
    font=dict(color="white")
)

# ─────────────────────────────
# SAVE HTML
# ─────────────────────────────
output_file = "task5_grouped_bar.html"
fig.write_html(output_file)

print(f"✅ HTML file created: {output_file}")

# ─────────────────────────────
# DOWNLOAD (COLAB)
# ─────────────────────────────
try:
    from google.colab import files
    files.download(output_file)
except:
    print("Download not supported in this environment.")