# -*- coding: utf-8 -*-
"""task_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng8bY3kHaCik2V2radTvjYVRc5r-fQAG
"""

#task 6
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz
import sys

# ─────────────────────────────
# TIME GATE (1 PM – 2 PM IST)
# ─────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now = datetime.now(ist)

if not (13 <= now.hour < 14):
    print("⛔ This graph is available only between 1 PM – 2 PM IST")
    sys.exit()

print("✅ Time condition satisfied")

# ─────────────────────────────
# LOAD DATA
# ─────────────────────────────
df = pd.read_csv("Play Store Data.csv")

# ─────────────────────────────
# CLEAN DATA
# ─────────────────────────────
df = df.dropna(subset=['Category', 'Installs', 'Price', 'Android Ver', 'Size', 'Content Rating', 'App'])

# Clean installs
df['Installs'] = (
    df['Installs'].astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

# Clean price → revenue calculation
df['Price'] = df['Price'].astype(str).str.replace('$', '', regex=False)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Revenue = Installs * Price
df['Revenue'] = df['Installs'] * df['Price']

# Extract Android version (first number)
df['Android_Ver'] = df['Android Ver'].str.extract(r'(\d+\.\d+)')
df['Android_Ver'] = pd.to_numeric(df['Android_Ver'], errors='coerce')

# Convert size
def convert_size(x):
    x = str(x)
    if 'M' in x:
        return float(x.replace('M', ''))
    elif 'k' in x:
        return float(x.replace('k', '')) / 1024
    return None

df['Size_MB'] = df['Size'].apply(convert_size)

# ─────────────────────────────
# APPLY FILTERS
# ─────────────────────────────

# Installs ≥ 10,000
df = df[df['Installs'] >= 10000]

# Revenue ≥ 10,000
df = df[df['Revenue'] >= 10000]

# Android version > 4.0
df = df[df['Android_Ver'] > 4.0]

# Size > 15MB
df = df[df['Size_MB'] > 15]

# Content Rating = Everyone
df = df[df['Content Rating'] == 'Everyone']

# App name ≤ 30 characters
df = df[df['App'].str.len() <= 30]

df = df.dropna(subset=['Installs', 'Revenue', 'Android_Ver', 'Size_MB'])

# ─────────────────────────────
# TOP 3 CATEGORIES BY INSTALLS
# ─────────────────────────────
top_categories = (
    df.groupby('Category')['Installs']
    .sum()
    .sort_values(ascending=False)
    .head(3)
    .index
)

df = df[df['Category'].isin(top_categories)]

# ─────────────────────────────
# AGGREGATION (FREE vs PAID)
# ─────────────────────────────
agg_df = df.groupby(['Category', 'Type']).agg(
    Avg_Installs=('Installs', 'mean'),
    Total_Revenue=('Revenue', 'sum')
).reset_index()

# ─────────────────────────────
# DUAL AXIS CHART
# ─────────────────────────────
fig = go.Figure()

# Avg installs (left axis)
fig.add_trace(go.Bar(
    x=agg_df['Category'] + " (" + agg_df['Type'] + ")",
    y=agg_df['Avg_Installs'],
    name='Average Installs',
    yaxis='y1'
))

# Revenue (right axis)
fig.add_trace(go.Scatter(
    x=agg_df['Category'] + " (" + agg_df['Type'] + ")",
    y=agg_df['Total_Revenue'],
    name='Revenue',
    yaxis='y2',
    mode='lines+markers'
))

# ─────────────────────────────
# LAYOUT
# ─────────────────────────────
fig.update_layout(
    title="Average Installs vs Revenue (Free vs Paid Apps)",
    xaxis_title="Category (App Type)",
    yaxis=dict(
        title="Average Installs",
        side='left'
    ),
    yaxis2=dict(
        title="Revenue ($)",
        overlaying='y',
        side='right'
    ),
    plot_bgcolor="#0a0e1a",
    paper_bgcolor="#111827",
    font=dict(color="white")
)

# ─────────────────────────────
# SAVE HTML
# ─────────────────────────────
output_file = "task6_dual_axis.html"
fig.write_html(output_file)

print(f"✅ HTML file created: {output_file}")

# ─────────────────────────────
# DOWNLOAD (COLAB)
# ─────────────────────────────
try:
    from google.colab import files
    files.download(output_file)
except:
    print("Download not supported in this environment.")