# -*- coding: utf-8 -*-
"""task_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6OQBoC845I7FhpwwHQnRKhuTIyK8v5J
"""

!pip install plotly pytz

import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz

apps = pd.read_csv("Play Store Data.csv")
reviews = pd.read_csv("googleplaystore_user_reviews.csv")

#task 1
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
from datetime import datetime
import pytz
import webbrowser
import os
import sys

# ─────────────────────────────────────────────
# TIME GATE (STRICT: 5 PM – 7 PM IST ONLY)
# ─────────────────────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now_ist = datetime.now(ist)
current_hour = now_ist.hour

if not (17 <= current_hour < 19):
    print("⛔ This dashboard is only available between 5 PM – 7 PM IST.")

    placeholder_html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
body {{ background:#0a0e1a; display:flex; align-items:center;
justify-content:center; height:100vh; margin:0;
font-family:'Segoe UI',sans-serif; color:#e2e8f0; }}
.box {{ text-align:center; border:1px solid #ef4444; border-radius:16px;
padding:60px 40px; background:#111827; max-width:500px; }}
h1 {{ color:#ef4444; }}
</style></head><body>
<div class="box">
<h1>Access Denied</h1>
<p>Available only between 5 PM – 7 PM IST</p>
<p>Current IST: {now_ist.strftime('%I:%M %p')}</p>
</div></body></html>"""

    with open("task1_bubble_chart.html", "w", encoding="utf-8") as f:
        f.write(placeholder_html)

    webbrowser.open('file://' + os.path.realpath("task1_bubble_chart.html"))
    sys.exit()

# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
apps_df = pd.read_csv('Play Store Data.csv')
reviews_df = pd.read_csv('User Reviews.csv')

# ─────────────────────────────────────────────
# DATA CLEANING
# ─────────────────────────────────────────────
apps_df = apps_df.dropna(subset=['Rating'])
apps_df = apps_df[apps_df['Rating'] <= 5]
apps_df.drop_duplicates(inplace=True)

apps_df['Reviews'] = pd.to_numeric(apps_df['Reviews'], errors='coerce')

apps_df['Installs'] = (
    apps_df['Installs'].astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)
apps_df['Installs'] = pd.to_numeric(apps_df['Installs'], errors='coerce')

def convert_size(size):
    size = str(size)
    if 'M' in size:
        return float(size.replace('M', ''))
    elif 'k' in size:
        return float(size.replace('k', '')) / 1024
    return np.nan

apps_df['Size'] = apps_df['Size'].apply(convert_size)

apps_df.dropna(subset=['Reviews', 'Installs', 'Size'], inplace=True)

# ─────────────────────────────────────────────
# SENTIMENT (VADER APPROXIMATION)
# ─────────────────────────────────────────────
nltk.download('vader_lexicon', quiet=True)
sia = SentimentIntensityAnalyzer()

reviews_df.dropna(subset=['Translated_Review'], inplace=True)

reviews_df['Sentiment_Subjectivity'] = reviews_df['Translated_Review'].apply(
    lambda x: abs(sia.polarity_scores(str(x))['compound'])
)

# ─────────────────────────────────────────────
# MERGE + AGGREGATE
# ─────────────────────────────────────────────
merged_df = pd.merge(
    apps_df[['App', 'Category', 'Rating', 'Reviews', 'Installs', 'Size']],
    reviews_df[['App', 'Sentiment_Subjectivity']],
    on='App', how='inner'
)

agg_df = merged_df.groupby(['App', 'Category', 'Size']).agg(
    Avg_Rating=('Rating', 'mean'),
    Total_Installs=('Installs', 'first'),
    Total_Reviews=('Reviews', 'first'),
    Avg_Subjectivity=('Sentiment_Subjectivity', 'mean')
).reset_index()

# ─────────────────────────────────────────────
# FILTERS
# ─────────────────────────────────────────────
allowed_categories = [
    'GAME', 'BEAUTY', 'BUSINESS', 'COMICS',
    'COMMUNICATION', 'DATING', 'ENTERTAINMENT',
    'SOCIAL', 'EVENTS'
]

agg_df = agg_df[
    (agg_df['Category'].str.upper().isin(allowed_categories)) &
    (agg_df['Avg_Rating'] > 3.5) &
    (agg_df['Total_Reviews'] > 500) &
    (agg_df['Total_Installs'] > 50000) &
    (agg_df['Avg_Subjectivity'] > 0.5) &
    (~agg_df['App'].str.contains('S', case=False, na=False))
]

if agg_df.empty:
    print("No data after filtering.")
    sys.exit()

# ─────────────────────────────────────────────
# TRANSLATIONS (FIXED)
# ─────────────────────────────────────────────
translation_map = {
    'BEAUTY': 'सौंदर्य (Beauty)',
    'BUSINESS': 'வணிகம் (Business)',   # ✅ FIXED
    'DATING': 'Partnersuche (Dating)',
    'GAME': 'Game',
    'COMICS': 'Comics',
    'COMMUNICATION': 'Communication',
    'ENTERTAINMENT': 'Entertainment',
    'SOCIAL': 'Social',
    'EVENTS': 'Events'
}

agg_df['Category_Label'] = agg_df['Category'].str.upper().map(translation_map)

# ─────────────────────────────────────────────
# BUBBLE SIZE
# ─────────────────────────────────────────────
max_installs = agg_df['Total_Installs'].max()
agg_df['Bubble_Size'] = (agg_df['Total_Installs'] / max_installs) * 60 + 8

# ─────────────────────────────────────────────
# COLOR MAP (GAME = PINK)
# ─────────────────────────────────────────────
color_map = {}
for cat in agg_df['Category_Label'].unique():
    if cat == 'Game':
        color_map[cat] = '#FF69B4'
    else:
        color_map[cat] = '#4cc9f0'

# ─────────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────────
fig = go.Figure()

for cat in agg_df['Category_Label'].unique():
    subset = agg_df[agg_df['Category_Label'] == cat]

    fig.add_trace(go.Scatter(
        x=subset['Size'],
        y=subset['Avg_Rating'],
        mode='markers',
        name=cat,
        marker=dict(
            size=subset['Bubble_Size'],
            color=color_map[cat],
            opacity=0.85
        ),
        text=subset['App'],
        hovertemplate="<b>%{text}</b><br>Size: %{x} MB<br>Rating: %{y}<extra></extra>"
    ))

fig.update_layout(
    title="App Size vs Average Rating (Bubble Size = Installs)",
    xaxis_title="App Size (MB)",
    yaxis_title="Average Rating",
    plot_bgcolor="#0a0e1a",
    paper_bgcolor="#111827",
    font=dict(color="white")
)

# ─────────────────────────────────────────────
# SAVE OUTPUT
# ─────────────────────────────────────────────
output_file = "task1_bubble_chart.html"
fig.write_html(output_file)
webbrowser.open('file://' + os.path.realpath(output_file))

print("✅ Dashboard generated successfully")