# -*- coding: utf-8 -*-
"""task_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng8bY3kHaCik2V2radTvjYVRc5r-fQAG
"""

#task 3
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz
import sys

# ─────────────────────────────
# TIME GATE (6 PM – 9 PM IST)
# ─────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now = datetime.now(ist)

if not (18 <= now.hour < 21):
    print("⛔ Available only between 6 PM – 9 PM IST")
    sys.exit()

print("✅ Time condition satisfied")

# ─────────────────────────────
# LOAD DATA
# ─────────────────────────────
df = pd.read_csv("Play Store Data.csv")

# ─────────────────────────────
# CLEAN DATA
# ─────────────────────────────
df = df.dropna(subset=['Category', 'Installs', 'Reviews', 'Last Updated'])

# Clean installs
df['Installs'] = (
    df['Installs'].astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')

# Convert date
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')

df = df.dropna(subset=['Installs', 'Reviews', 'Last Updated'])

# ─────────────────────────────
# APPLY FILTERS
# ─────────────────────────────

# Reviews > 500
df = df[df['Reviews'] > 500]

# App name should NOT start with x,y,z
df = df[~df['App'].str.lower().str.startswith(('x', 'y', 'z'))]

# App name should NOT contain 'S'
df = df[~df['App'].str.contains('s', case=False, na=False)]

# Category must start with E, C, B
df = df[df['Category'].str.upper().str.startswith(('E', 'C', 'B'))]

# ─────────────────────────────
# TRANSLATION
# ─────────────────────────────
translation = {
    'BEAUTY': 'सौंदर्य',
    'BUSINESS': 'வணிகம்',
    'DATING': 'Partnersuche'
}

df['Category_Display'] = df['Category'].str.upper().replace(translation)

# ─────────────────────────────
# TIME SERIES PREPARATION
# ─────────────────────────────
df['Month'] = df['Last Updated'].dt.to_period('M').dt.to_timestamp()

agg_df = df.groupby(['Month', 'Category_Display'])['Installs'].sum().reset_index()

# Sort properly
agg_df = agg_df.sort_values(['Category_Display', 'Month'])

# ─────────────────────────────
# CALCULATE GROWTH
# ─────────────────────────────
agg_df['Growth'] = agg_df.groupby('Category_Display')['Installs'].pct_change()

# Mark significant growth > 20%
agg_df['High_Growth'] = agg_df['Growth'] > 0.2

# ─────────────────────────────
# PLOT
# ─────────────────────────────
fig = go.Figure()

categories = agg_df['Category_Display'].unique()

for cat in categories:
    subset = agg_df[agg_df['Category_Display'] == cat]

    # Line plot
    fig.add_trace(go.Scatter(
        x=subset['Month'],
        y=subset['Installs'],
        mode='lines+markers',
        name=cat
    ))

    # Highlight area where growth > 20%
    high_growth = subset[subset['High_Growth']]

    fig.add_trace(go.Scatter(
        x=high_growth['Month'],
        y=high_growth['Installs'],
        fill='tozeroy',
        mode='none',
        name=f"{cat} High Growth",
        opacity=0.2,
        showlegend=False
    ))

# ─────────────────────────────
# LAYOUT
# ─────────────────────────────
fig.update_layout(
    title="Monthly Installs Trend by Category<br><sup>Highlighted: >20% Growth</sup>",
    xaxis_title="Time (Month)",
    yaxis_title="Total Installs",
    plot_bgcolor="#0a0e1a",
    paper_bgcolor="#111827",
    font=dict(color="white")
)

# ─────────────────────────────
# SAVE HTML
# ─────────────────────────────
output_file = "task3_timeseries.html"
fig.write_html(output_file)

print(f"✅ HTML file created: {output_file}")

# ─────────────────────────────
# DOWNLOAD (COLAB)
# ─────────────────────────────
try:
    from google.colab import files
    files.download(output_file)
except:
    print("Download not supported in this environment.")