# -*- coding: utf-8 -*-
"""task_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng8bY3kHaCik2V2radTvjYVRc5r-fQAG
"""

#task 2
import pandas as pd
import plotly.express as px
from datetime import datetime
import pytz
import sys

# ─────────────────────────────
# TIME GATE (6 PM – 8 PM IST)
# ─────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now = datetime.now(ist)

if not (18 <= now.hour < 20):
    print("⛔ This map is available only between 6 PM – 8 PM IST.")
    sys.exit()

print("✅ Time condition satisfied")

# ─────────────────────────────
# LOAD DATA
# ─────────────────────────────
df = pd.read_csv("Play Store Data.csv")

# ─────────────────────────────
# CLEAN DATA
# ─────────────────────────────
df = df.dropna(subset=['Category', 'Installs'])

df['Installs'] = df['Installs'].astype(str)
df['Installs'] = df['Installs'].str.replace(',', '', regex=False)
df['Installs'] = df['Installs'].str.replace('+', '', regex=False)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

df = df.dropna(subset=['Installs'])

# ─────────────────────────────
# FILTER CATEGORY NAMES
# ─────────────────────────────
df = df[~df['Category'].str.upper().str.startswith(('A', 'C', 'G', 'S'))]

# ─────────────────────────────
# TOP 5 CATEGORIES
# ─────────────────────────────
top_categories = (
    df.groupby('Category')['Installs']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index
)

df = df[df['Category'].isin(top_categories)]

# ─────────────────────────────
# AGGREGATE
# ─────────────────────────────
agg_df = df.groupby('Category')['Installs'].sum().reset_index()

# Dummy country mapping
countries = ['United States', 'India', 'Brazil', 'Germany', 'United Kingdom']
agg_df['Country'] = countries[:len(agg_df)]

# ─────────────────────────────
# HIGHLIGHT (>1M INSTALLS)
# ─────────────────────────────
agg_df['Highlight'] = agg_df['Installs'].apply(
    lambda x: 'Above 1M' if x > 1_000_000 else 'Below 1M'
)

# ─────────────────────────────
# CHOROPLETH MAP
# ─────────────────────────────
fig = px.choropleth(
    agg_df,
    locations="Country",
    locationmode="country names",
    color="Installs",   # keep gradient (looks better)
    hover_name="Category",
    hover_data=["Installs", "Highlight"],  # 🔥 highlight visible here
    color_continuous_scale="Plasma",
    title="Global Installs by Top 5 App Categories<br><sup>Highlight: >1M installs</sup>"
)

# Add border highlight for >1M installs
fig.update_traces(
    marker_line_width=2,
    marker_line_color="white"
)

# ─────────────────────────────
# SAVE HTML
# ─────────────────────────────
output_file = "task2_choropleth_map.html"
fig.write_html(output_file)

print(f"✅ HTML file created: {output_file}")

# ─────────────────────────────
# DOWNLOAD (COLAB)
# ─────────────────────────────
try:
    from google.colab import files
    files.download(output_file)
except:
    print("Download not supported in this environment.")