# -*- coding: utf-8 -*-
"""task_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng8bY3kHaCik2V2radTvjYVRc5r-fQAG
"""

#task 4
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime
import pytz
import sys

# ─────────────────────────────
# TIME GATE (4 PM – 6 PM IST)
# ─────────────────────────────
ist = pytz.timezone('Asia/Kolkata')
now = datetime.now(ist)

if not (16 <= now.hour < 18):
    print("⛔ This visualization is available only between 4 PM – 6 PM IST")
    sys.exit()

print("✅ Time condition satisfied")

# ─────────────────────────────
# LOAD DATA
# ─────────────────────────────
df = pd.read_csv("Play Store Data.csv")

# ─────────────────────────────
# CLEAN DATA
# ─────────────────────────────
df = df.dropna(subset=['Category', 'Installs', 'Reviews', 'Size', 'Rating', 'Last Updated'])

# Clean installs
df['Installs'] = (
    df['Installs'].astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('+', '', regex=False)
)
df['Installs'] = pd.to_numeric(df['Installs'], errors='coerce')

# Reviews & Rating
df['Reviews'] = pd.to_numeric(df['Reviews'], errors='coerce')
df['Rating'] = pd.to_numeric(df['Rating'], errors='coerce')

# Convert Size to MB
def convert_size(x):
    x = str(x)
    if 'M' in x:
        return float(x.replace('M', ''))
    elif 'k' in x:
        return float(x.replace('k', '')) / 1024
    return None

df['Size_MB'] = df['Size'].apply(convert_size)

# Convert Date
df['Last Updated'] = pd.to_datetime(df['Last Updated'], errors='coerce')

df = df.dropna(subset=['Installs', 'Reviews', 'Rating', 'Size_MB', 'Last Updated'])

# ─────────────────────────────
# APPLY FILTERS
# ─────────────────────────────

# Rating ≥ 4.2
df = df[df['Rating'] >= 4.2]

# App name should NOT contain numbers
df = df[~df['App'].str.contains(r'\d', na=False)]

# Category starts with T or P
df = df[df['Category'].str.upper().str.startswith(('T', 'P'))]

# Reviews > 1000
df = df[df['Reviews'] > 1000]

# Size between 20MB and 80MB
df = df[(df['Size_MB'] >= 20) & (df['Size_MB'] <= 80)]

# ─────────────────────────────
# TRANSLATIONS
# ─────────────────────────────
translation = {
    'TRAVEL & LOCAL': 'Voyage et Local',   # French
    'PRODUCTIVITY': 'Productividad',       # Spanish
    'PHOTOGRAPHY': '写真'                  # Japanese
}

df['Category_Display'] = df['Category'].str.upper().replace(translation)

# ─────────────────────────────
# TIME SERIES PREPARATION
# ─────────────────────────────
df['Month'] = df['Last Updated'].dt.to_period('M').dt.to_timestamp()

agg_df = df.groupby(['Month', 'Category_Display'])['Installs'].sum().reset_index()

agg_df = agg_df.sort_values(['Category_Display', 'Month'])

# ─────────────────────────────
# GROWTH CALCULATION (>25%)
# ─────────────────────────────
agg_df['Growth'] = agg_df.groupby('Category_Display')['Installs'].pct_change()
agg_df['High_Growth'] = agg_df['Growth'] > 0.25

# ─────────────────────────────
# STACKED AREA CHART
# ─────────────────────────────
fig = go.Figure()

for cat in agg_df['Category_Display'].unique():
    subset = agg_df[agg_df['Category_Display'] == cat]

    fig.add_trace(go.Scatter(
        x=subset['Month'],
        y=subset['Installs'],
        mode='lines',
        stackgroup='one',
        name=cat
    ))

# Highlight high growth points
high = agg_df[agg_df['High_Growth']]

fig.add_trace(go.Scatter(
    x=high['Month'],
    y=high['Installs'],
    mode='markers',
    marker=dict(size=8, color='red'),
    name='High Growth (>25%)'
))

# ─────────────────────────────
# LAYOUT
# ─────────────────────────────
fig.update_layout(
    title="Cumulative Installs Over Time by Category<br><sup>Highlight: >25% Month-over-Month Growth</sup>",
    xaxis_title="Month",
    yaxis_title="Total Installs",
    plot_bgcolor="#0a0e1a",
    paper_bgcolor="#111827",
    font=dict(color="white")
)

# ─────────────────────────────
# SAVE HTML
# ─────────────────────────────
output_file = "task4_stacked_area.html"
fig.write_html(output_file)

print(f"✅ HTML file created: {output_file}")

# ─────────────────────────────
# DOWNLOAD (COLAB)
# ─────────────────────────────
try:
    from google.colab import files
    files.download(output_file)
except:
    print("Download not supported in this environment.")